server.port: 10101
mes.url: 127.0.0.1:8006
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        tags: urlprefix-/${spring.application.name}
        instanceId: ${spring.application.name}:${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: relsend
        uri: http://127.0.0.1:9999
        predicates:
          [{"args": { "pattern": "/callMESFunction"},"name": "Path"},{'args':{"method":"POST"},"name":"Method"},{"args":{"inClass":"java.lang.String","Predicate":"#{@truePredicate}"},"name":"ReadBodyPredicateFactory"}]
      - id: dofunction
        uri: http://127.0.0.1:9999
        predicates:
          [{"args": { "pattern": "/dofunction"},"name": "Path"},{'args':{"method":"POST"},"name":"Method"},{"args":{"inClass":"java.lang.String","Predicate":"#{@truePredicate}"},"name":"ReadBodyPredicateFactory"}]
      - id: getSchemaList
        uri: http://127.0.0.1:8006
        predicates: 
          [{"args": { "pattern": "/getBaseMsg/getSchemaList"},      "name": "Path"}]
      - id: getSchemaList
        uri: http://127.0.0.1:8006
        predicates:
          [{"args": { "pattern": "/getBaseMsg/getEmpNoByNt"},      "name": "Path"}]
      - id: getLoginEmergencyFlag
        uri: http://127.0.0.1:8006
        predicates:
          [{"args": { "pattern": "/getBaseMsg/getLoginEmergencyFlag"},      "name": "Path"}]
      - id: getLoginEmergencyFlag
        uri: http://127.0.0.1:8006
        predicates:
          [{"args": { "pattern": "/getBaseMsg/logMesUserInfo"},      "name": "Path"}]
   
 
# 配置输出日志
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

#开启端点
management:
  endpoints:
    web:
      exposure:
        include: ['route','gateway','health']
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  server:
    port: 9090